//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BDO_Localisation_AddOn.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://nbg.gov.ge/currency_service.php")]
        public string BDO_Localisation_AddOn_WayBillService_HTTP_NBGCurrencyService {
            get {
                return ((string)(this["BDO_Localisation_AddOn_WayBillService_HTTP_NBGCurrencyService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://services.rs.ge/WayBillService/WayBillService.asmx")]
        public string BDO_Localisation_AddOn_WayBillService_HTTP_WayBills {
            get {
                return ((string)(this["BDO_Localisation_AddOn_WayBillService_HTTP_WayBills"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://services.rs.ge/taxservice/taxservice.asmx")]
        public string BDO_Localisation_AddOn_TaxService_HTTP_Service {
            get {
                return ((string)(this["BDO_Localisation_AddOn_TaxService_HTTP_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://services.rs.ge/WayBillService/WayBillService.asmx")]
        public string BDO_Localisation_AddOn_WayBillService_HTTPS_WayBills {
            get {
                return ((string)(this["BDO_Localisation_AddOn_WayBillService_HTTPS_WayBills"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.revenue.mof.ge/ntosservice/ntosservice.asmx")]
        public string BDO_Localisation_AddOn_RSInvoiceService_HTTP_NtosService {
            get {
                return ((string)(this["BDO_Localisation_AddOn_RSInvoiceService_HTTP_NtosService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.revenue.mof.ge/ntosservice/ntosservice.asmx")]
        public string BDO_Localisation_AddOn_RSInvoiceService_HTTPS_NtosService {
            get {
                return ((string)(this["BDO_Localisation_AddOn_RSInvoiceService_HTTPS_NtosService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://update.ibs.ge/UpdateConfigs/ws/UpdateConfig.1cws")]
        public string BDO_Localisation_AddOn_ge_ibs_update_ПроверкаОбновленииКонфигурации {
            get {
                return ((string)(this["BDO_Localisation_AddOn_ge_ibs_update_ПроверкаОбновленииКонфигурации"]));
            }
        }
    }
}
