//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace BDO_Localisation_AddOn.TaxService_HTTP {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSoap", Namespace="services.rs.ge")]
    public partial class Service : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetTPNameByINOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTerminalAutoInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTPInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTPInfoCIOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTPInfoDPAOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTPInfoDebt_RSOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTPEmployersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTPEmployersAmountOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTPIncomeInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTPFamilyOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsPersonDebtorOperationCompleted;
        
        private System.Threading.SendOrPostCallback IsPersonDebtor2OperationCompleted;
        
        private System.Threading.SendOrPostCallback GetIdentificationNumbersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GerRegistrationOrganOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetLienInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTerminalAutoNotifyOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTPInfoGovOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTPInfoGovDeaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service() {
            this.Url = global::BDO_Localisation_AddOn.Properties.Settings.Default.BDO_Localisation_AddOn_TaxService_HTTP_Service;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetTPNameByINCompletedEventHandler GetTPNameByINCompleted;
        
        /// <remarks/>
        public event GetTerminalAutoInfoCompletedEventHandler GetTerminalAutoInfoCompleted;
        
        /// <remarks/>
        public event GetTPInfoCompletedEventHandler GetTPInfoCompleted;
        
        /// <remarks/>
        public event GetTPInfoCICompletedEventHandler GetTPInfoCICompleted;
        
        /// <remarks/>
        public event GetTPInfoDPACompletedEventHandler GetTPInfoDPACompleted;
        
        /// <remarks/>
        public event GetTPInfoDebt_RSCompletedEventHandler GetTPInfoDebt_RSCompleted;
        
        /// <remarks/>
        public event GetTPEmployersCompletedEventHandler GetTPEmployersCompleted;
        
        /// <remarks/>
        public event GetTPEmployersAmountCompletedEventHandler GetTPEmployersAmountCompleted;
        
        /// <remarks/>
        public event GetTPIncomeInfoCompletedEventHandler GetTPIncomeInfoCompleted;
        
        /// <remarks/>
        public event GetTPFamilyCompletedEventHandler GetTPFamilyCompleted;
        
        /// <remarks/>
        public event IsPersonDebtorCompletedEventHandler IsPersonDebtorCompleted;
        
        /// <remarks/>
        public event IsPersonDebtor2CompletedEventHandler IsPersonDebtor2Completed;
        
        /// <remarks/>
        public event GetIdentificationNumbersCompletedEventHandler GetIdentificationNumbersCompleted;
        
        /// <remarks/>
        public event GerRegistrationOrganCompletedEventHandler GerRegistrationOrganCompleted;
        
        /// <remarks/>
        public event GetLienInfoCompletedEventHandler GetLienInfoCompleted;
        
        /// <remarks/>
        public event GetTerminalAutoNotifyCompletedEventHandler GetTerminalAutoNotifyCompleted;
        
        /// <remarks/>
        public event GetTPInfoGovCompletedEventHandler GetTPInfoGovCompleted;
        
        /// <remarks/>
        public event GetTPInfoGovDeaCompletedEventHandler GetTPInfoGovDeaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("services.rs.ge/GetTPNameByIN", RequestNamespace="services.rs.ge", ResponseNamespace="services.rs.ge", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TPInfo GetTPNameByIN(string IN) {
            object[] results = this.Invoke("GetTPNameByIN", new object[] {
                        IN});
            return ((TPInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetTPNameByINAsync(string IN) {
            this.GetTPNameByINAsync(IN, null);
        }
        
        /// <remarks/>
        public void GetTPNameByINAsync(string IN, object userState) {
            if ((this.GetTPNameByINOperationCompleted == null)) {
                this.GetTPNameByINOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTPNameByINOperationCompleted);
            }
            this.InvokeAsync("GetTPNameByIN", new object[] {
                        IN}, this.GetTPNameByINOperationCompleted, userState);
        }
        
        private void OnGetTPNameByINOperationCompleted(object arg) {
            if ((this.GetTPNameByINCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTPNameByINCompleted(this, new GetTPNameByINCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("services.rs.ge/GetTerminalAutoInfo", RequestNamespace="services.rs.ge", ResponseNamespace="services.rs.ge", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TerminalAutoInfo[] GetTerminalAutoInfo(string login, string password, System.DateTime Date) {
            object[] results = this.Invoke("GetTerminalAutoInfo", new object[] {
                        login,
                        password,
                        Date});
            return ((TerminalAutoInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTerminalAutoInfoAsync(string login, string password, System.DateTime Date) {
            this.GetTerminalAutoInfoAsync(login, password, Date, null);
        }
        
        /// <remarks/>
        public void GetTerminalAutoInfoAsync(string login, string password, System.DateTime Date, object userState) {
            if ((this.GetTerminalAutoInfoOperationCompleted == null)) {
                this.GetTerminalAutoInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTerminalAutoInfoOperationCompleted);
            }
            this.InvokeAsync("GetTerminalAutoInfo", new object[] {
                        login,
                        password,
                        Date}, this.GetTerminalAutoInfoOperationCompleted, userState);
        }
        
        private void OnGetTerminalAutoInfoOperationCompleted(object arg) {
            if ((this.GetTerminalAutoInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTerminalAutoInfoCompleted(this, new GetTerminalAutoInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("services.rs.ge/GetTPInfo", RequestNamespace="services.rs.ge", ResponseNamespace="services.rs.ge", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ExtendedTPInfo GetTPInfo(string login, string password, string IN) {
            object[] results = this.Invoke("GetTPInfo", new object[] {
                        login,
                        password,
                        IN});
            return ((ExtendedTPInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetTPInfoAsync(string login, string password, string IN) {
            this.GetTPInfoAsync(login, password, IN, null);
        }
        
        /// <remarks/>
        public void GetTPInfoAsync(string login, string password, string IN, object userState) {
            if ((this.GetTPInfoOperationCompleted == null)) {
                this.GetTPInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTPInfoOperationCompleted);
            }
            this.InvokeAsync("GetTPInfo", new object[] {
                        login,
                        password,
                        IN}, this.GetTPInfoOperationCompleted, userState);
        }
        
        private void OnGetTPInfoOperationCompleted(object arg) {
            if ((this.GetTPInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTPInfoCompleted(this, new GetTPInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("services.rs.ge/GetTPInfoCI", RequestNamespace="services.rs.ge", ResponseNamespace="services.rs.ge", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TPInfo_CI GetTPInfoCI(string login, string password, string IN) {
            object[] results = this.Invoke("GetTPInfoCI", new object[] {
                        login,
                        password,
                        IN});
            return ((TPInfo_CI)(results[0]));
        }
        
        /// <remarks/>
        public void GetTPInfoCIAsync(string login, string password, string IN) {
            this.GetTPInfoCIAsync(login, password, IN, null);
        }
        
        /// <remarks/>
        public void GetTPInfoCIAsync(string login, string password, string IN, object userState) {
            if ((this.GetTPInfoCIOperationCompleted == null)) {
                this.GetTPInfoCIOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTPInfoCIOperationCompleted);
            }
            this.InvokeAsync("GetTPInfoCI", new object[] {
                        login,
                        password,
                        IN}, this.GetTPInfoCIOperationCompleted, userState);
        }
        
        private void OnGetTPInfoCIOperationCompleted(object arg) {
            if ((this.GetTPInfoCICompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTPInfoCICompleted(this, new GetTPInfoCICompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("services.rs.ge/GetTPInfoDPA", RequestNamespace="services.rs.ge", ResponseNamespace="services.rs.ge", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TPInfo_DPA GetTPInfoDPA(string login, string password, string IN) {
            object[] results = this.Invoke("GetTPInfoDPA", new object[] {
                        login,
                        password,
                        IN});
            return ((TPInfo_DPA)(results[0]));
        }
        
        /// <remarks/>
        public void GetTPInfoDPAAsync(string login, string password, string IN) {
            this.GetTPInfoDPAAsync(login, password, IN, null);
        }
        
        /// <remarks/>
        public void GetTPInfoDPAAsync(string login, string password, string IN, object userState) {
            if ((this.GetTPInfoDPAOperationCompleted == null)) {
                this.GetTPInfoDPAOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTPInfoDPAOperationCompleted);
            }
            this.InvokeAsync("GetTPInfoDPA", new object[] {
                        login,
                        password,
                        IN}, this.GetTPInfoDPAOperationCompleted, userState);
        }
        
        private void OnGetTPInfoDPAOperationCompleted(object arg) {
            if ((this.GetTPInfoDPACompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTPInfoDPACompleted(this, new GetTPInfoDPACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("services.rs.ge/GetTPInfoDebt_RS", RequestNamespace="services.rs.ge", ResponseNamespace="services.rs.ge", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public TPInfoDebt_RS[] GetTPInfoDebt_RS(string login, string password) {
            object[] results = this.Invoke("GetTPInfoDebt_RS", new object[] {
                        login,
                        password});
            return ((TPInfoDebt_RS[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTPInfoDebt_RSAsync(string login, string password) {
            this.GetTPInfoDebt_RSAsync(login, password, null);
        }
        
        /// <remarks/>
        public void GetTPInfoDebt_RSAsync(string login, string password, object userState) {
            if ((this.GetTPInfoDebt_RSOperationCompleted == null)) {
                this.GetTPInfoDebt_RSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTPInfoDebt_RSOperationCompleted);
            }
            this.InvokeAsync("GetTPInfoDebt_RS", new object[] {
                        login,
                        password}, this.GetTPInfoDebt_RSOperationCompleted, userState);
        }
        
        private void OnGetTPInfoDebt_RSOperationCompleted(object arg) {
            if ((this.GetTPInfoDebt_RSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTPInfoDebt_RSCompleted(this, new GetTPInfoDebt_RSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("services.rs.ge/GetTPEmployers", RequestNamespace="services.rs.ge", ResponseNamespace="services.rs.ge", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EmployerInfo[] GetTPEmployers(string login, string password, string IN) {
            object[] results = this.Invoke("GetTPEmployers", new object[] {
                        login,
                        password,
                        IN});
            return ((EmployerInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTPEmployersAsync(string login, string password, string IN) {
            this.GetTPEmployersAsync(login, password, IN, null);
        }
        
        /// <remarks/>
        public void GetTPEmployersAsync(string login, string password, string IN, object userState) {
            if ((this.GetTPEmployersOperationCompleted == null)) {
                this.GetTPEmployersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTPEmployersOperationCompleted);
            }
            this.InvokeAsync("GetTPEmployers", new object[] {
                        login,
                        password,
                        IN}, this.GetTPEmployersOperationCompleted, userState);
        }
        
        private void OnGetTPEmployersOperationCompleted(object arg) {
            if ((this.GetTPEmployersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTPEmployersCompleted(this, new GetTPEmployersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("services.rs.ge/GetTPEmployersAmount", RequestNamespace="services.rs.ge", ResponseNamespace="services.rs.ge", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public EmployerAmountInfo[] GetTPEmployersAmount(string login, string password, string IN) {
            object[] results = this.Invoke("GetTPEmployersAmount", new object[] {
                        login,
                        password,
                        IN});
            return ((EmployerAmountInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTPEmployersAmountAsync(string login, string password, string IN) {
            this.GetTPEmployersAmountAsync(login, password, IN, null);
        }
        
        /// <remarks/>
        public void GetTPEmployersAmountAsync(string login, string password, string IN, object userState) {
            if ((this.GetTPEmployersAmountOperationCompleted == null)) {
                this.GetTPEmployersAmountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTPEmployersAmountOperationCompleted);
            }
            this.InvokeAsync("GetTPEmployersAmount", new object[] {
                        login,
                        password,
                        IN}, this.GetTPEmployersAmountOperationCompleted, userState);
        }
        
        private void OnGetTPEmployersAmountOperationCompleted(object arg) {
            if ((this.GetTPEmployersAmountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTPEmployersAmountCompleted(this, new GetTPEmployersAmountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("services.rs.ge/GetTPIncomeInfo", RequestNamespace="services.rs.ge", ResponseNamespace="services.rs.ge", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public IncomeInfo[] GetTPIncomeInfo(string login, string password, string IN, int Year) {
            object[] results = this.Invoke("GetTPIncomeInfo", new object[] {
                        login,
                        password,
                        IN,
                        Year});
            return ((IncomeInfo[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTPIncomeInfoAsync(string login, string password, string IN, int Year) {
            this.GetTPIncomeInfoAsync(login, password, IN, Year, null);
        }
        
        /// <remarks/>
        public void GetTPIncomeInfoAsync(string login, string password, string IN, int Year, object userState) {
            if ((this.GetTPIncomeInfoOperationCompleted == null)) {
                this.GetTPIncomeInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTPIncomeInfoOperationCompleted);
            }
            this.InvokeAsync("GetTPIncomeInfo", new object[] {
                        login,
                        password,
                        IN,
                        Year}, this.GetTPIncomeInfoOperationCompleted, userState);
        }
        
        private void OnGetTPIncomeInfoOperationCompleted(object arg) {
            if ((this.GetTPIncomeInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTPIncomeInfoCompleted(this, new GetTPIncomeInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("services.rs.ge/GetTPFamily", RequestNamespace="services.rs.ge", ResponseNamespace="services.rs.ge", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public FamilyInfo GetTPFamily(string login, string password, string IN) {
            object[] results = this.Invoke("GetTPFamily", new object[] {
                        login,
                        password,
                        IN});
            return ((FamilyInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetTPFamilyAsync(string login, string password, string IN) {
            this.GetTPFamilyAsync(login, password, IN, null);
        }
        
        /// <remarks/>
        public void GetTPFamilyAsync(string login, string password, string IN, object userState) {
            if ((this.GetTPFamilyOperationCompleted == null)) {
                this.GetTPFamilyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTPFamilyOperationCompleted);
            }
            this.InvokeAsync("GetTPFamily", new object[] {
                        login,
                        password,
                        IN}, this.GetTPFamilyOperationCompleted, userState);
        }
        
        private void OnGetTPFamilyOperationCompleted(object arg) {
            if ((this.GetTPFamilyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTPFamilyCompleted(this, new GetTPFamilyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("services.rs.ge/IsPersonDebtor", RequestNamespace="services.rs.ge", ResponseNamespace="services.rs.ge", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DebtorInfo IsPersonDebtor(string login, string password, string IdenificationNumber, string PersonalNumber, string Name, string Surname, string DoB) {
            object[] results = this.Invoke("IsPersonDebtor", new object[] {
                        login,
                        password,
                        IdenificationNumber,
                        PersonalNumber,
                        Name,
                        Surname,
                        DoB});
            return ((DebtorInfo)(results[0]));
        }
        
        /// <remarks/>
        public void IsPersonDebtorAsync(string login, string password, string IdenificationNumber, string PersonalNumber, string Name, string Surname, string DoB) {
            this.IsPersonDebtorAsync(login, password, IdenificationNumber, PersonalNumber, Name, Surname, DoB, null);
        }
        
        /// <remarks/>
        public void IsPersonDebtorAsync(string login, string password, string IdenificationNumber, string PersonalNumber, string Name, string Surname, string DoB, object userState) {
            if ((this.IsPersonDebtorOperationCompleted == null)) {
                this.IsPersonDebtorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsPersonDebtorOperationCompleted);
            }
            this.InvokeAsync("IsPersonDebtor", new object[] {
                        login,
                        password,
                        IdenificationNumber,
                        PersonalNumber,
                        Name,
                        Surname,
                        DoB}, this.IsPersonDebtorOperationCompleted, userState);
        }
        
        private void OnIsPersonDebtorOperationCompleted(object arg) {
            if ((this.IsPersonDebtorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsPersonDebtorCompleted(this, new IsPersonDebtorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("services.rs.ge/IsPersonDebtor2", RequestNamespace="services.rs.ge", ResponseNamespace="services.rs.ge", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public DebtorInfo IsPersonDebtor2(string login, string password, string IdenificationNumber, string PersonalNumber, string Name, string Surname, string DoB, string Muxli) {
            object[] results = this.Invoke("IsPersonDebtor2", new object[] {
                        login,
                        password,
                        IdenificationNumber,
                        PersonalNumber,
                        Name,
                        Surname,
                        DoB,
                        Muxli});
            return ((DebtorInfo)(results[0]));
        }
        
        /// <remarks/>
        public void IsPersonDebtor2Async(string login, string password, string IdenificationNumber, string PersonalNumber, string Name, string Surname, string DoB, string Muxli) {
            this.IsPersonDebtor2Async(login, password, IdenificationNumber, PersonalNumber, Name, Surname, DoB, Muxli, null);
        }
        
        /// <remarks/>
        public void IsPersonDebtor2Async(string login, string password, string IdenificationNumber, string PersonalNumber, string Name, string Surname, string DoB, string Muxli, object userState) {
            if ((this.IsPersonDebtor2OperationCompleted == null)) {
                this.IsPersonDebtor2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnIsPersonDebtor2OperationCompleted);
            }
            this.InvokeAsync("IsPersonDebtor2", new object[] {
                        login,
                        password,
                        IdenificationNumber,
                        PersonalNumber,
                        Name,
                        Surname,
                        DoB,
                        Muxli}, this.IsPersonDebtor2OperationCompleted, userState);
        }
        
        private void OnIsPersonDebtor2OperationCompleted(object arg) {
            if ((this.IsPersonDebtor2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IsPersonDebtor2Completed(this, new IsPersonDebtor2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("services.rs.ge/GetIdentificationNumbers", RequestNamespace="services.rs.ge", ResponseNamespace="services.rs.ge", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetIdentificationNumbers(string login, string password, string Name, string SurName, string OrganisationName) {
            object[] results = this.Invoke("GetIdentificationNumbers", new object[] {
                        login,
                        password,
                        Name,
                        SurName,
                        OrganisationName});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void GetIdentificationNumbersAsync(string login, string password, string Name, string SurName, string OrganisationName) {
            this.GetIdentificationNumbersAsync(login, password, Name, SurName, OrganisationName, null);
        }
        
        /// <remarks/>
        public void GetIdentificationNumbersAsync(string login, string password, string Name, string SurName, string OrganisationName, object userState) {
            if ((this.GetIdentificationNumbersOperationCompleted == null)) {
                this.GetIdentificationNumbersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetIdentificationNumbersOperationCompleted);
            }
            this.InvokeAsync("GetIdentificationNumbers", new object[] {
                        login,
                        password,
                        Name,
                        SurName,
                        OrganisationName}, this.GetIdentificationNumbersOperationCompleted, userState);
        }
        
        private void OnGetIdentificationNumbersOperationCompleted(object arg) {
            if ((this.GetIdentificationNumbersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetIdentificationNumbersCompleted(this, new GetIdentificationNumbersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("services.rs.ge/GerRegistrationOrgan", RequestNamespace="services.rs.ge", ResponseNamespace="services.rs.ge", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GerRegistrationOrgan(string login, string password, string IdentificationNumber) {
            object[] results = this.Invoke("GerRegistrationOrgan", new object[] {
                        login,
                        password,
                        IdentificationNumber});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GerRegistrationOrganAsync(string login, string password, string IdentificationNumber) {
            this.GerRegistrationOrganAsync(login, password, IdentificationNumber, null);
        }
        
        /// <remarks/>
        public void GerRegistrationOrganAsync(string login, string password, string IdentificationNumber, object userState) {
            if ((this.GerRegistrationOrganOperationCompleted == null)) {
                this.GerRegistrationOrganOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGerRegistrationOrganOperationCompleted);
            }
            this.InvokeAsync("GerRegistrationOrgan", new object[] {
                        login,
                        password,
                        IdentificationNumber}, this.GerRegistrationOrganOperationCompleted, userState);
        }
        
        private void OnGerRegistrationOrganOperationCompleted(object arg) {
            if ((this.GerRegistrationOrganCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GerRegistrationOrganCompleted(this, new GerRegistrationOrganCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("services.rs.ge/GetLienInfo", RequestNamespace="services.rs.ge", ResponseNamespace="services.rs.ge", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LienInfo GetLienInfo(string login, string password, string IN) {
            object[] results = this.Invoke("GetLienInfo", new object[] {
                        login,
                        password,
                        IN});
            return ((LienInfo)(results[0]));
        }
        
        /// <remarks/>
        public void GetLienInfoAsync(string login, string password, string IN) {
            this.GetLienInfoAsync(login, password, IN, null);
        }
        
        /// <remarks/>
        public void GetLienInfoAsync(string login, string password, string IN, object userState) {
            if ((this.GetLienInfoOperationCompleted == null)) {
                this.GetLienInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetLienInfoOperationCompleted);
            }
            this.InvokeAsync("GetLienInfo", new object[] {
                        login,
                        password,
                        IN}, this.GetLienInfoOperationCompleted, userState);
        }
        
        private void OnGetLienInfoOperationCompleted(object arg) {
            if ((this.GetLienInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetLienInfoCompleted(this, new GetLienInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("services.rs.ge/GetTerminalAutoNotify", RequestNamespace="services.rs.ge", ResponseNamespace="services.rs.ge", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable GetTerminalAutoNotify(string login, string password, int barcode) {
            object[] results = this.Invoke("GetTerminalAutoNotify", new object[] {
                        login,
                        password,
                        barcode});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void GetTerminalAutoNotifyAsync(string login, string password, int barcode) {
            this.GetTerminalAutoNotifyAsync(login, password, barcode, null);
        }
        
        /// <remarks/>
        public void GetTerminalAutoNotifyAsync(string login, string password, int barcode, object userState) {
            if ((this.GetTerminalAutoNotifyOperationCompleted == null)) {
                this.GetTerminalAutoNotifyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTerminalAutoNotifyOperationCompleted);
            }
            this.InvokeAsync("GetTerminalAutoNotify", new object[] {
                        login,
                        password,
                        barcode}, this.GetTerminalAutoNotifyOperationCompleted, userState);
        }
        
        private void OnGetTerminalAutoNotifyOperationCompleted(object arg) {
            if ((this.GetTerminalAutoNotifyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTerminalAutoNotifyCompleted(this, new GetTerminalAutoNotifyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("services.rs.ge/GetTPInfoGov", RequestNamespace="services.rs.ge", ResponseNamespace="services.rs.ge", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResponseTPInfoGov GetTPInfoGov(string Username, string Password, string OrgCode, string OrgName) {
            object[] results = this.Invoke("GetTPInfoGov", new object[] {
                        Username,
                        Password,
                        OrgCode,
                        OrgName});
            return ((ResponseTPInfoGov)(results[0]));
        }
        
        /// <remarks/>
        public void GetTPInfoGovAsync(string Username, string Password, string OrgCode, string OrgName) {
            this.GetTPInfoGovAsync(Username, Password, OrgCode, OrgName, null);
        }
        
        /// <remarks/>
        public void GetTPInfoGovAsync(string Username, string Password, string OrgCode, string OrgName, object userState) {
            if ((this.GetTPInfoGovOperationCompleted == null)) {
                this.GetTPInfoGovOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTPInfoGovOperationCompleted);
            }
            this.InvokeAsync("GetTPInfoGov", new object[] {
                        Username,
                        Password,
                        OrgCode,
                        OrgName}, this.GetTPInfoGovOperationCompleted, userState);
        }
        
        private void OnGetTPInfoGovOperationCompleted(object arg) {
            if ((this.GetTPInfoGovCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTPInfoGovCompleted(this, new GetTPInfoGovCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("services.rs.ge/GetTPInfoGovDea", RequestNamespace="services.rs.ge", ResponseNamespace="services.rs.ge", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ResponseTPInfoGovDea GetTPInfoGovDea(string Username, string Password, string TP_Code) {
            object[] results = this.Invoke("GetTPInfoGovDea", new object[] {
                        Username,
                        Password,
                        TP_Code});
            return ((ResponseTPInfoGovDea)(results[0]));
        }
        
        /// <remarks/>
        public void GetTPInfoGovDeaAsync(string Username, string Password, string TP_Code) {
            this.GetTPInfoGovDeaAsync(Username, Password, TP_Code, null);
        }
        
        /// <remarks/>
        public void GetTPInfoGovDeaAsync(string Username, string Password, string TP_Code, object userState) {
            if ((this.GetTPInfoGovDeaOperationCompleted == null)) {
                this.GetTPInfoGovDeaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTPInfoGovDeaOperationCompleted);
            }
            this.InvokeAsync("GetTPInfoGovDea", new object[] {
                        Username,
                        Password,
                        TP_Code}, this.GetTPInfoGovDeaOperationCompleted, userState);
        }
        
        private void OnGetTPInfoGovDeaOperationCompleted(object arg) {
            if ((this.GetTPInfoGovDeaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTPInfoGovDeaCompleted(this, new GetTPInfoGovDeaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="services.rs.ge")]
    public partial class TPInfo {
        
        private string nameField;
        
        private string addressField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="services.rs.ge")]
    public partial class TPInfoGovDea {
        
        private string tP_CodeField;
        
        private string tP_NameField;
        
        private string tP_AddressField;
        
        private string tP_LegalFormField;
        
        /// <remarks/>
        public string TP_Code {
            get {
                return this.tP_CodeField;
            }
            set {
                this.tP_CodeField = value;
            }
        }
        
        /// <remarks/>
        public string TP_Name {
            get {
                return this.tP_NameField;
            }
            set {
                this.tP_NameField = value;
            }
        }
        
        /// <remarks/>
        public string TP_Address {
            get {
                return this.tP_AddressField;
            }
            set {
                this.tP_AddressField = value;
            }
        }
        
        /// <remarks/>
        public string TP_LegalForm {
            get {
                return this.tP_LegalFormField;
            }
            set {
                this.tP_LegalFormField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="services.rs.ge")]
    public partial class ResponseTPInfoGovDea {
        
        private Response responseField;
        
        private TPInfoGovDea tPInfoGovDeaInfoField;
        
        /// <remarks/>
        public Response Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
        
        /// <remarks/>
        public TPInfoGovDea TPInfoGovDeaInfo {
            get {
                return this.tPInfoGovDeaInfoField;
            }
            set {
                this.tPInfoGovDeaInfoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="services.rs.ge")]
    public partial class Response {
        
        private bool responseStatusField;
        
        private ErrorDetails errorField;
        
        /// <remarks/>
        public bool ResponseStatus {
            get {
                return this.responseStatusField;
            }
            set {
                this.responseStatusField = value;
            }
        }
        
        /// <remarks/>
        public ErrorDetails Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="services.rs.ge")]
    public partial class ErrorDetails {
        
        private int errorCodeField;
        
        private string errorDescriptionField;
        
        /// <remarks/>
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        public string ErrorDescription {
            get {
                return this.errorDescriptionField;
            }
            set {
                this.errorDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="services.rs.ge")]
    public partial class TPInfoGov {
        
        private string organizationNameField;
        
        private string identificatinCodeField;
        
        private string legalAddressField;
        
        private string statusField;
        
        /// <remarks/>
        public string OrganizationName {
            get {
                return this.organizationNameField;
            }
            set {
                this.organizationNameField = value;
            }
        }
        
        /// <remarks/>
        public string IdentificatinCode {
            get {
                return this.identificatinCodeField;
            }
            set {
                this.identificatinCodeField = value;
            }
        }
        
        /// <remarks/>
        public string LegalAddress {
            get {
                return this.legalAddressField;
            }
            set {
                this.legalAddressField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="services.rs.ge")]
    public partial class ResponseTPInfoGov {
        
        private Response responseField;
        
        private TPInfoGov[] tPInfoGovListField;
        
        /// <remarks/>
        public Response Response {
            get {
                return this.responseField;
            }
            set {
                this.responseField = value;
            }
        }
        
        /// <remarks/>
        public TPInfoGov[] TPInfoGovList {
            get {
                return this.tPInfoGovListField;
            }
            set {
                this.tPInfoGovListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="services.rs.ge")]
    public partial class LienInfo {
        
        private string saIdentNoField;
        
        private string nameField;
        
        private System.DateTime dateField;
        
        private System.DateTime dateEndField;
        
        /// <remarks/>
        public string SaIdentNo {
            get {
                return this.saIdentNoField;
            }
            set {
                this.saIdentNoField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime Date {
            get {
                return this.dateField;
            }
            set {
                this.dateField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DateEnd {
            get {
                return this.dateEndField;
            }
            set {
                this.dateEndField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="services.rs.ge")]
    public partial class DebtorInfo {
        
        private string lastStatusChangedDateField;
        
        private string statusField;
        
        private string documentNumberField;
        
        private string textField;
        
        private string status_FineField;
        
        /// <remarks/>
        public string LastStatusChangedDate {
            get {
                return this.lastStatusChangedDateField;
            }
            set {
                this.lastStatusChangedDateField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string DocumentNumber {
            get {
                return this.documentNumberField;
            }
            set {
                this.documentNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        public string Status_Fine {
            get {
                return this.status_FineField;
            }
            set {
                this.status_FineField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="services.rs.ge")]
    public partial class FamilyInfo {
        
        private string personField;
        
        private string fatherField;
        
        private string motherField;
        
        private string[] sistersField;
        
        private string[] brothersField;
        
        private string[] childrenField;
        
        /// <remarks/>
        public string Person {
            get {
                return this.personField;
            }
            set {
                this.personField = value;
            }
        }
        
        /// <remarks/>
        public string Father {
            get {
                return this.fatherField;
            }
            set {
                this.fatherField = value;
            }
        }
        
        /// <remarks/>
        public string Mother {
            get {
                return this.motherField;
            }
            set {
                this.motherField = value;
            }
        }
        
        /// <remarks/>
        public string[] Sisters {
            get {
                return this.sistersField;
            }
            set {
                this.sistersField = value;
            }
        }
        
        /// <remarks/>
        public string[] Brothers {
            get {
                return this.brothersField;
            }
            set {
                this.brothersField = value;
            }
        }
        
        /// <remarks/>
        public string[] Children {
            get {
                return this.childrenField;
            }
            set {
                this.childrenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="services.rs.ge")]
    public partial class IncomeInfo {
        
        private string personIDField;
        
        private double amount1Field;
        
        private double amount2Field;
        
        private int statusField;
        
        private int statusOtherField;
        
        private string[] otherListField;
        
        /// <remarks/>
        public string PersonID {
            get {
                return this.personIDField;
            }
            set {
                this.personIDField = value;
            }
        }
        
        /// <remarks/>
        public double Amount1 {
            get {
                return this.amount1Field;
            }
            set {
                this.amount1Field = value;
            }
        }
        
        /// <remarks/>
        public double Amount2 {
            get {
                return this.amount2Field;
            }
            set {
                this.amount2Field = value;
            }
        }
        
        /// <remarks/>
        public int Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public int StatusOther {
            get {
                return this.statusOtherField;
            }
            set {
                this.statusOtherField = value;
            }
        }
        
        /// <remarks/>
        public string[] OtherList {
            get {
                return this.otherListField;
            }
            set {
                this.otherListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="services.rs.ge")]
    public partial class EmployerAmountInfo {
        
        private string personIDField;
        
        private string personNameField;
        
        private string organizationField;
        
        private string yearField;
        
        private double amountField;
        
        /// <remarks/>
        public string PersonID {
            get {
                return this.personIDField;
            }
            set {
                this.personIDField = value;
            }
        }
        
        /// <remarks/>
        public string PersonName {
            get {
                return this.personNameField;
            }
            set {
                this.personNameField = value;
            }
        }
        
        /// <remarks/>
        public string Organization {
            get {
                return this.organizationField;
            }
            set {
                this.organizationField = value;
            }
        }
        
        /// <remarks/>
        public string Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
        
        /// <remarks/>
        public double Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="services.rs.ge")]
    public partial class EmployerInfo {
        
        private string personIDField;
        
        private string personNameField;
        
        private string organizationField;
        
        private string yearField;
        
        /// <remarks/>
        public string PersonID {
            get {
                return this.personIDField;
            }
            set {
                this.personIDField = value;
            }
        }
        
        /// <remarks/>
        public string PersonName {
            get {
                return this.personNameField;
            }
            set {
                this.personNameField = value;
            }
        }
        
        /// <remarks/>
        public string Organization {
            get {
                return this.organizationField;
            }
            set {
                this.organizationField = value;
            }
        }
        
        /// <remarks/>
        public string Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="services.rs.ge")]
    public partial class TPInfoDebt_RS {
        
        private string codeField;
        
        private double debtAmountField;
        
        /// <remarks/>
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        public double DebtAmount {
            get {
                return this.debtAmountField;
            }
            set {
                this.debtAmountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="services.rs.ge")]
    public partial class TPInfo_DPA {
        
        private string nameField;
        
        private string addressField;
        
        private string telField;
        
        private string emailField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string Tel {
            get {
                return this.telField;
            }
            set {
                this.telField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="services.rs.ge")]
    public partial class TPInfo_CI {
        
        private string nameField;
        
        private double debtField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public double Debt {
            get {
                return this.debtField;
            }
            set {
                this.debtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="services.rs.ge")]
    public partial class ExtendedTPInfo {
        
        private string nameField;
        
        private string addressField;
        
        private string organizationTypeField;
        
        private string organizationTypeShortField;
        
        private string activityTypeField;
        
        private string registrationNumberField;
        
        private string notesField;
        
        private System.DateTime lastRegistrationChangeField;
        
        private System.DateTime registrationDateField;
        
        private string statusField;
        
        private string saIdentNoField;
        
        private string personIdField;
        
        private System.Data.DataSet representativesField;
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string OrganizationType {
            get {
                return this.organizationTypeField;
            }
            set {
                this.organizationTypeField = value;
            }
        }
        
        /// <remarks/>
        public string OrganizationTypeShort {
            get {
                return this.organizationTypeShortField;
            }
            set {
                this.organizationTypeShortField = value;
            }
        }
        
        /// <remarks/>
        public string ActivityType {
            get {
                return this.activityTypeField;
            }
            set {
                this.activityTypeField = value;
            }
        }
        
        /// <remarks/>
        public string RegistrationNumber {
            get {
                return this.registrationNumberField;
            }
            set {
                this.registrationNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Notes {
            get {
                return this.notesField;
            }
            set {
                this.notesField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LastRegistrationChange {
            get {
                return this.lastRegistrationChangeField;
            }
            set {
                this.lastRegistrationChangeField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime RegistrationDate {
            get {
                return this.registrationDateField;
            }
            set {
                this.registrationDateField = value;
            }
        }
        
        /// <remarks/>
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        public string SaIdentNo {
            get {
                return this.saIdentNoField;
            }
            set {
                this.saIdentNoField = value;
            }
        }
        
        /// <remarks/>
        public string PersonId {
            get {
                return this.personIdField;
            }
            set {
                this.personIdField = value;
            }
        }
        
        /// <remarks/>
        public System.Data.DataSet Representatives {
            get {
                return this.representativesField;
            }
            set {
                this.representativesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1087.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="services.rs.ge")]
    public partial class TerminalAutoInfo {
        
        private string personal_noField;
        
        private string gov_numberField;
        
        private string auto_vinField;
        
        private System.DateTime cross_dateField;
        
        private int division_idField;
        
        private int durationField;
        
        private string transit_number_saagField;
        
        private int terminal_idField;
        
        private string owner_codeField;
        
        private string owner_nameField;
        
        /// <remarks/>
        public string personal_no {
            get {
                return this.personal_noField;
            }
            set {
                this.personal_noField = value;
            }
        }
        
        /// <remarks/>
        public string gov_number {
            get {
                return this.gov_numberField;
            }
            set {
                this.gov_numberField = value;
            }
        }
        
        /// <remarks/>
        public string auto_vin {
            get {
                return this.auto_vinField;
            }
            set {
                this.auto_vinField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime cross_date {
            get {
                return this.cross_dateField;
            }
            set {
                this.cross_dateField = value;
            }
        }
        
        /// <remarks/>
        public int division_id {
            get {
                return this.division_idField;
            }
            set {
                this.division_idField = value;
            }
        }
        
        /// <remarks/>
        public int duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
            }
        }
        
        /// <remarks/>
        public string transit_number_saag {
            get {
                return this.transit_number_saagField;
            }
            set {
                this.transit_number_saagField = value;
            }
        }
        
        /// <remarks/>
        public int terminal_id {
            get {
                return this.terminal_idField;
            }
            set {
                this.terminal_idField = value;
            }
        }
        
        /// <remarks/>
        public string owner_code {
            get {
                return this.owner_codeField;
            }
            set {
                this.owner_codeField = value;
            }
        }
        
        /// <remarks/>
        public string owner_name {
            get {
                return this.owner_nameField;
            }
            set {
                this.owner_nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetTPNameByINCompletedEventHandler(object sender, GetTPNameByINCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTPNameByINCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTPNameByINCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TPInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TPInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetTerminalAutoInfoCompletedEventHandler(object sender, GetTerminalAutoInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTerminalAutoInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTerminalAutoInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TerminalAutoInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TerminalAutoInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetTPInfoCompletedEventHandler(object sender, GetTPInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTPInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTPInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ExtendedTPInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ExtendedTPInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetTPInfoCICompletedEventHandler(object sender, GetTPInfoCICompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTPInfoCICompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTPInfoCICompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TPInfo_CI Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TPInfo_CI)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetTPInfoDPACompletedEventHandler(object sender, GetTPInfoDPACompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTPInfoDPACompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTPInfoDPACompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TPInfo_DPA Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TPInfo_DPA)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetTPInfoDebt_RSCompletedEventHandler(object sender, GetTPInfoDebt_RSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTPInfoDebt_RSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTPInfoDebt_RSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public TPInfoDebt_RS[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((TPInfoDebt_RS[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetTPEmployersCompletedEventHandler(object sender, GetTPEmployersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTPEmployersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTPEmployersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EmployerInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EmployerInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetTPEmployersAmountCompletedEventHandler(object sender, GetTPEmployersAmountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTPEmployersAmountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTPEmployersAmountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public EmployerAmountInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((EmployerAmountInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetTPIncomeInfoCompletedEventHandler(object sender, GetTPIncomeInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTPIncomeInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTPIncomeInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public IncomeInfo[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((IncomeInfo[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetTPFamilyCompletedEventHandler(object sender, GetTPFamilyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTPFamilyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTPFamilyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public FamilyInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((FamilyInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void IsPersonDebtorCompletedEventHandler(object sender, IsPersonDebtorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsPersonDebtorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsPersonDebtorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DebtorInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DebtorInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void IsPersonDebtor2CompletedEventHandler(object sender, IsPersonDebtor2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IsPersonDebtor2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IsPersonDebtor2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DebtorInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DebtorInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetIdentificationNumbersCompletedEventHandler(object sender, GetIdentificationNumbersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetIdentificationNumbersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetIdentificationNumbersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GerRegistrationOrganCompletedEventHandler(object sender, GerRegistrationOrganCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GerRegistrationOrganCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GerRegistrationOrganCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetLienInfoCompletedEventHandler(object sender, GetLienInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetLienInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetLienInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LienInfo Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LienInfo)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetTerminalAutoNotifyCompletedEventHandler(object sender, GetTerminalAutoNotifyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTerminalAutoNotifyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTerminalAutoNotifyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetTPInfoGovCompletedEventHandler(object sender, GetTPInfoGovCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTPInfoGovCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTPInfoGovCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseTPInfoGov Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseTPInfoGov)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    public delegate void GetTPInfoGovDeaCompletedEventHandler(object sender, GetTPInfoGovDeaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.1087.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTPInfoGovDeaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTPInfoGovDeaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public ResponseTPInfoGovDea Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((ResponseTPInfoGovDea)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591